- name: restart_fluentd-stackdriver
  systemd:
    state: restarted
    name: fluentd-stackdriver
    daemon_reload: yes

- name: restart_dockerd
  systemd:
    state: restarted
    name: dockerd
    daemon_reload: yes
