- name: Ensure docker.io package installed
  apt:
    name: docker.io
    state: present

- name: Docker systemd config directory
  file:
    path: /etc/systemd/system/docker.service.d/
    mode: 0755
    state: directory
  when: proxy_env is defined

- name: Docker proxy settings
  copy:
    src: 99-proxy.conf
    dest: /etc/systemd/system/docker.service.d/99-proxy.conf
  when: proxy_env is defined
  notify:
    - restart_dockerd

- name: Ensure /opt/naisdevice/fluentd-stackdriver/ directory
  file:
    path: /opt/naisdevice/fluentd-stackdriver/
    state: directory
    mode: 0755

- name: Download google cloud log write SA credentials
  shell:
    cmd: gcloud --project nais-device secrets versions access latest --secret logwriter-credentials > /opt/naisdevice/fluentd-stackdriver/sa.json
    creates: /opt/naisdevice/fluentd-stackdriver/sa.json

- name: Copy fluentd systemd unit
  copy:
    src: fluentd-stackdriver.service
    dest: /etc/systemd/system/fluentd-stackdriver.service
    mode: '0644'
  notify:
    - restart_fluentd-stackdriver

- name: Start and enable fluentd
  systemd:
    name: fluentd-stackdriver
    state: started
    enabled: yes
    daemon_reload: yes
