- name: Ensure docker.io package installed
  apt:
    name: docker.io
    state: present

- name: Docker systemd config directory
  file:
    path: /etc/systemd/system/docker.service.d/
    mode: 0755
    state: directory
  when: proxy_env is defined

- name: Docker proxy settings
  copy:
    src: 99-proxy.conf
    dest: /etc/systemd/system/docker.service.d/99-proxy.conf
  when: proxy_env is defined
  notify:
    - restart_dockerd

- name: Download google cloud log write SA credentials
  shell:
    cmd: gcloud --project nais-device secrets versions access latest --secret logwriter-credentials > /root/sa_tmp.json && mv /root/sa{_tmp,}.json
    creates: /root/sa.json

- name: Copy fluentd systemd unit
  copy:
    src: fluentd-stackdriver.service
    dest: /etc/systemd/system/fluentd-stackdriver.service
    mode: '0644'
  notify:
    - restart_fluentd-stackdriver

- name: Start and enable fluentd
  systemd:
    name: fluentd-stackdriver
    state: stopped
    enabled: no
    daemon_reload: yes
