---
- hosts: bootstrap_api
  roles:
    - logging
    - bootstrap-api

- hosts: prometheus
  roles:
    - logging
    - prometheus

- hosts: apiservers
  roles:
    - logging
    - apiserver

- hosts: gateways
  roles:
    - logging
    - gateway

- hosts: onprem_gateways
  environment: "{{ proxy_env }}"
  roles:
    - onprem-gateway
    - logging
    - gateway
