name: Kolide checks severity
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  validate:
    defaults:
      run:
        working-directory: ./device-health-checker
    name: Validate Kolide checks severity tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-ansi -o --no-dev

      - name: Validate Kolide checks
        id: validate-checks
        run: php device-health-checker.php kolide:validate-checks -t $KOLIDE_API_TOKEN
        env:
          KOLIDE_API_TOKEN: ${{ secrets.KOLIDE_API_TOKEN }}

      - name: Alert the Slack channel if the validation failed
        if: failure()
        run: php notify-slack.php
        env:
          INCOMPLETE_CHECKS: ${{ steps.validate-checks.outputs.incomplete-checks }}
          SLACK_WEBHOOK: ${{ secrets.KOLIDE_CHECKS_VALIDATION_SLACK_WEBHOOK }}